import { PROFILE_ID_PATTERN } from "./paths.js";

export const BEGIN_MARKER_PREFIX = "### BEGIN SHAREDGITIGNORE";
export const END_MARKER_PREFIX = "### END SHAREDGITIGNORE";
export const END_MARKER = "### END SHAREDGITIGNORE - PROJECT RULES BELOW ###";
const PROFILE_ID_SOURCE = PROFILE_ID_PATTERN.source.slice(1, -1);
export const BEGIN_MARKER_PATTERN = new RegExp(
  `^### BEGIN SHAREDGITIGNORE profile=(${PROFILE_ID_SOURCE}) version=1 ###$`
);

function splitLines(text) {
  const lines = [];
  let index = 0;

  while (index < text.length) {
    let nextNewline = text.indexOf("\n", index);
    let endingLength = 0;
    if (nextNewline === -1) {
      nextNewline = text.length;
    } else {
      endingLength = 1;
      if (nextNewline > index && text[nextNewline - 1] === "\r") {
        endingLength = 2;
      }
    }

    const end = nextNewline + (endingLength === 0 ? 0 : 1);
    const raw = text.slice(index, end);
    const lineEnd = endingLength === 2 ? raw.length - 2 : (endingLength === 1 ? raw.length - 1 : raw.length);
    lines.push({
      raw,
      text: raw.slice(0, lineEnd),
      start: index,
      end
    });
    index = end;
  }

  return lines;
}

export function beginMarker(profile) {
  if (typeof profile !== "string" || !PROFILE_ID_PATTERN.test(profile)) {
    throw new Error(`invalid profile id: ${profile}`);
  }
  return `### BEGIN SHAREDGITIGNORE profile=${profile} version=1 ###`;
}

export function renderBlock(profile, templateContent) {
  let output = `${beginMarker(profile)}\n`;
  output += "# DO NOT EDIT. Generated by sharedgitignore.\n";
  output += "# Run: sharedgitignore sync\n\n";
  output += templateContent;
  if (templateContent.length > 0 && !templateContent.endsWith("\n")) output += "\n";
  output += `${END_MARKER}\n`;
  return output;
}

export function renderGitignore(profile, templateContent, projectContent = "") {
  return renderBlock(profile, templateContent) + projectContent;
}

export function renderGitignoreBuffer(profile, templateContent, projectContent = Buffer.alloc(0)) {
  if (!Buffer.isBuffer(templateContent)) throw new TypeError("template content must be a Buffer");
  if (!Buffer.isBuffer(projectContent)) throw new TypeError("project content must be a Buffer");

  const parts = [
    Buffer.from(`${beginMarker(profile)}\n`),
    Buffer.from("# DO NOT EDIT. Generated by sharedgitignore.\n"),
    Buffer.from("# Run: sharedgitignore sync\n\n"),
    templateContent
  ];
  if (templateContent.length > 0 && templateContent.at(-1) !== 0x0a) {
    parts.push(Buffer.from("\n"));
  }
  parts.push(Buffer.from(`${END_MARKER}\n`), projectContent);
  return Buffer.concat(parts);
}

function contentView(content) {
  if (Buffer.isBuffer(content)) {
    return {
      text: content.toString("latin1"),
      sliceProject(start) {
        return Buffer.from(content.subarray(start));
      }
    };
  }
  if (typeof content !== "string") throw new TypeError("gitignore content must be a string or Buffer");
  return {
    text: content,
    sliceProject(start) {
      return content.slice(start);
    }
  };
}

export function hasReservedMarkerPrefix(content) {
  const { text } = contentView(content);
  return splitLines(text).some((line) => (
    line.text.startsWith(BEGIN_MARKER_PREFIX) || line.text.startsWith(END_MARKER_PREFIX)
  ));
}

export function validateTemplateContent(content) {
  if (typeof content !== "string") throw new TypeError("template content must be a string");
  const errors = [];
  if (content.includes("\u0000")) errors.push("template must not contain NUL bytes");
  if (content.includes("\ufeff")) errors.push("template must not contain a byte-order mark");

  const lines = splitLines(content);
  for (let index = 0; index < lines.length; index += 1) {
    const line = lines[index].text;
    if (line.startsWith(BEGIN_MARKER_PREFIX) || line.startsWith(END_MARKER_PREFIX)) {
      errors.push(`template contains reserved sharedgitignore marker at line ${index + 1}`);
    }
  }
  return errors;
}

export function parseGitignore(content) {
  const view = contentView(content);
  const lines = splitLines(view.text);
  const beginMatches = [];
  const endMatches = [];
  const errors = [];

  for (let index = 0; index < lines.length; index += 1) {
    const line = lines[index].text;
    if (line.startsWith(BEGIN_MARKER_PREFIX)) {
      const beginMatch = line.match(BEGIN_MARKER_PATTERN);
      if (beginMatch) beginMatches.push({ index, profile: beginMatch[1], line: lines[index] });
      else errors.push(`malformed sharedgitignore begin marker at line ${index + 1}`);
    }
    if (line.startsWith(END_MARKER_PREFIX)) {
      if (line === END_MARKER) endMatches.push({ index, line: lines[index] });
      else errors.push(`malformed sharedgitignore end marker at line ${index + 1}`);
    }
  }

  if (beginMatches.length > 1) errors.push("duplicate sharedgitignore begin markers");
  if (endMatches.length > 1) errors.push("duplicate sharedgitignore end markers");
  if (beginMatches.length === 0 && endMatches.length > 0) errors.push("missing sharedgitignore begin marker");

  if (beginMatches.length === 0) {
    return {
      hasBlock: false,
      profile: null,
      projectContent: view.sliceProject(0),
      errors
    };
  }

  const begin = beginMatches[0];
  const firstNonEmptyIndex = lines.findIndex((line) => line.text.trim() !== "");
  if (firstNonEmptyIndex !== begin.index) {
    errors.push("sharedgitignore begin marker must be the first non-empty line");
  }

  const end = endMatches.find((candidate) => candidate.index > begin.index);
  if (!end) {
    errors.push("missing sharedgitignore end marker");
    return {
      hasBlock: true,
      profile: begin.profile,
      projectContent: view.sliceProject(view.text.length),
      errors
    };
  }

  return {
    hasBlock: true,
    profile: begin.profile,
    projectContent: view.sliceProject(end.line.end),
    errors
  };
}
