import { PROFILE_ID_PATTERN } from "./paths.js";

export const END_MARKER = "### END SHAREDGITIGNORE - PROJECT RULES BELOW ###";
export const BEGIN_MARKER_PATTERN = /^### BEGIN SHAREDGITIGNORE profile=([a-z0-9][a-z0-9._-]*) version=1 ###$/;

function splitLines(text) {
  const lines = [];
  let index = 0;

  while (index < text.length) {
    let nextNewline = text.indexOf("\n", index);
    let endingLength = 0;
    if (nextNewline === -1) {
      nextNewline = text.length;
    } else {
      endingLength = 1;
      if (nextNewline > index && text[nextNewline - 1] === "\r") {
        endingLength = 2;
      }
    }

    const end = nextNewline + (endingLength === 0 ? 0 : 1);
    const raw = text.slice(index, end);
    const lineEnd = endingLength === 2 ? raw.length - 2 : (endingLength === 1 ? raw.length - 1 : raw.length);
    lines.push({
      raw,
      text: raw.slice(0, lineEnd),
      start: index,
      end
    });
    index = end;
  }

  return lines;
}

export function beginMarker(profile) {
  if (!PROFILE_ID_PATTERN.test(profile)) {
    throw new Error(`invalid profile id: ${profile}`);
  }
  return `### BEGIN SHAREDGITIGNORE profile=${profile} version=1 ###`;
}

export function renderBlock(profile, templateContent) {
  let output = `${beginMarker(profile)}\n`;
  output += "# DO NOT EDIT. Generated by sharedgitignore.\n";
  output += "# Run: sharedgitignore sync\n\n";
  output += templateContent;
  if (templateContent.length > 0 && !templateContent.endsWith("\n")) output += "\n";
  output += `${END_MARKER}\n`;
  return output;
}

export function renderGitignore(profile, templateContent, projectContent = "") {
  return renderBlock(profile, templateContent) + projectContent;
}

export function parseGitignore(content) {
  const lines = splitLines(content);
  const beginMatches = [];
  const endMatches = [];

  for (let index = 0; index < lines.length; index += 1) {
    const beginMatch = lines[index].text.match(BEGIN_MARKER_PATTERN);
    if (beginMatch) beginMatches.push({ index, profile: beginMatch[1], line: lines[index] });
    if (lines[index].text === END_MARKER) endMatches.push({ index, line: lines[index] });
  }

  const errors = [];
  if (beginMatches.length > 1) errors.push("duplicate sharedgitignore begin markers");
  if (endMatches.length > 1) errors.push("duplicate sharedgitignore end markers");
  if (beginMatches.length === 0 && endMatches.length > 0) errors.push("missing sharedgitignore begin marker");

  if (beginMatches.length === 0) {
    return {
      hasBlock: false,
      profile: null,
      projectContent: content,
      errors
    };
  }

  const begin = beginMatches[0];
  const firstNonEmptyIndex = lines.findIndex((line) => line.text.trim() !== "");
  if (firstNonEmptyIndex !== begin.index) {
    errors.push("sharedgitignore begin marker must be the first non-empty line");
  }

  const end = endMatches.find((candidate) => candidate.index > begin.index);
  if (!end) {
    errors.push("missing sharedgitignore end marker");
    return {
      hasBlock: true,
      profile: begin.profile,
      projectContent: "",
      errors
    };
  }

  return {
    hasBlock: true,
    profile: begin.profile,
    projectContent: content.slice(end.line.end),
    errors
  };
}
