import os from "node:os";
import path from "node:path";
import { atomicWriteFile, ensureDir } from "./paths.js";

export function zshCompletionScript() {
  return [
    "#compdef sharedgitignore",
    "",
    "_sharedgitignore_profile_ids() {",
    "  local -a profile_ids",
    "  profile_ids=(\"${(@f)$(sharedgitignore profile list 2>/dev/null | awk -F '\\t' 'NF == 2 { print $1 }')}\")",
    "  if (( ${#profile_ids[@]} )); then",
    "    compadd -a profile_ids",
    "  fi",
    "}",
    "",
    "_sharedgitignore_top_commands() {",
    "  local -a commands",
    "  commands=(",
    "    'profile:manage shared gitignore profiles'",
    "    'detect:inspect the current repository'",
    "    'init:initialize a repository managed block'",
    "    'sync:update a managed block'",
    "    'check:verify a managed block is current'",
    "    'sync-all:update managed repos under a root'",
    "    'check-all:verify managed repos under a root'",
    "    'completion:print or install shell completions'",
    "    'help:show help'",
    "  )",
    "  _describe -t commands 'sharedgitignore command' commands",
    "  compadd -- --help --version",
    "}",
    "",
    "_sharedgitignore_profile_commands() {",
    "  local -a commands",
    "  commands=(",
    "    'add:register a shared gitignore profile'",
    "    'remove:remove a shared gitignore profile'",
    "    'list:list registered profiles'",
    "    'status:show profile health'",
    "  )",
    "  _describe -t commands 'profile command' commands",
    "}",
    "",
    "_sharedgitignore_completion_commands() {",
    "  local -a commands",
    "  commands=(",
    "    'zsh:print zsh completion script'",
    "    'install:install zsh completion file'",
    "  )",
    "  _describe -t commands 'completion command' commands",
    "}",
    "",
    "_sharedgitignore() {",
    "  local previous=\"${words[$((CURRENT - 1))]}\"",
    "",
    "  if [[ \"$previous\" == '--cwd' || \"$previous\" == '--root' || \"$previous\" == '--dir' ]]; then",
    "    _files -/",
    "    return",
    "  fi",
    "",
    "  if [[ \"$previous\" == '--profile' ]]; then",
    "    _sharedgitignore_profile_ids",
    "    return",
    "  fi",
    "",
    "  if (( CURRENT == 2 )); then",
    "    _sharedgitignore_top_commands",
    "    return",
    "  fi",
    "",
    "  case \"${words[2]}\" in",
    "    profile)",
    "      if (( CURRENT == 3 )); then",
    "        _sharedgitignore_profile_commands",
    "        return",
    "      fi",
    "      case \"${words[3]}\" in",
    "        add)",
    "          if (( CURRENT == 5 )); then _files; fi",
    "          ;;",
    "        remove)",
    "          if (( CURRENT >= 4 )); then _sharedgitignore_profile_ids; fi",
    "          ;;",
    "      esac",
    "      ;;",
    "    detect)",
    "      compadd -- --cwd --json",
    "      ;;",
    "    init)",
    "      compadd -- --profile --cwd --dry-run",
    "      ;;",
    "    sync)",
    "      compadd -- --cwd --dry-run",
    "      ;;",
    "    check)",
    "      compadd -- --cwd",
    "      ;;",
    "    sync-all|check-all)",
    "      if [[ \"${words[2]}\" == 'sync-all' ]]; then",
    "        compadd -- --root --no-recursive --dry-run",
    "      else",
    "        compadd -- --root --no-recursive",
    "      fi",
    "      ;;",
    "    completion)",
    "      if (( CURRENT == 3 )); then",
    "        _sharedgitignore_completion_commands",
    "        return",
    "      fi",
    "      if [[ \"${words[3]}\" == 'install' ]]; then",
    "        compadd -- --dir",
    "      fi",
    "      ;;",
    "  esac",
    "}",
    "",
    "_sharedgitignore \"$@\"",
    ""
  ].join("\n");
}

export function defaultZshCompletionDir(env = process.env) {
  return path.resolve(env.SHAREDGITIGNORE_ZSH_COMPLETION_DIR || path.join(env.HOME || os.homedir(), ".zsh", "completions"));
}

export function installZshCompletion({ dir, env = process.env } = {}) {
  const targetDir = path.resolve(dir || defaultZshCompletionDir(env));
  ensureDir(targetDir);
  const filePath = path.join(targetDir, "_sharedgitignore");
  atomicWriteFile(filePath, zshCompletionScript());
  return { shell: "zsh", filePath };
}
